### ISSUE TITLE
Get dedicated server working?

### ISSUE THREAD

**Issue by xRaid96** [angaityel/wotr-re#1]
First of all: thank you for your great work. Is there any chance to get the wotr_server.exe working to let a dedicated server run in the background on a windows server machine?

**Comment by angaityel** [comment]
~I haven't tested much yet.~
~Server endlessly reconnects to backend and does not show up in server browser/join tab.~

~Still, if you want to check it out:~
~Create steam_appid.txt in game folder with wotr appid 42160~
~Run with .\wotr_server.exe -bundle-dir bundle -ini dedicated_server_settings~

~It connects to steam.~
~It is VAC secured (or at least logs says so, "anti_cheat enforce" from server_settings.ini seems to be only for EAC).~
~It is not visible in server browser/join tab, but when server is running, "Server 0 failed to respond" appears in game logs. Most likely because server is locked until connection to backend is established. I haven't been able to unlock it manually yet.~

This is now possible, check the readme.
